package guiPack;

import java.io.File;
import java.util.Arrays;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import preprocess.*;
import algoritmo.*;
public class Jframe_Form extends javax.swing.JFrame {

    public Jframe_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        seletorArq = new javax.swing.JButton();
        filePath = new javax.swing.JTextField();
        RLinear = new javax.swing.JRadioButton();
        RLogistica = new javax.swing.JRadioButton();
        arvoreD = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        soTeste = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        seletorArq.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        seletorArq.setText("Selecione um arquivo");
        seletorArq.setToolTipText("");
        seletorArq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorArqActionPerformed(evt);
            }
        });

        filePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathActionPerformed(evt);
            }
        });

        buttonGroup1.add(RLinear);
        RLinear.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        RLinear.setText("Regressão linear");
        RLinear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RLinearActionPerformed(evt);
            }
        });

        buttonGroup1.add(RLogistica);
        RLogistica.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        RLogistica.setText("Regressão Logistica");
        RLogistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RLogisticaActionPerformed(evt);
            }
        });

        buttonGroup1.add(arvoreD);
        arvoreD.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        arvoreD.setText("Arvore de decisões");
        arvoreD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arvoreDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("Selecione um algoritmo: ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Modelo da regressão: ");

        soTeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soTesteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(seletorArq)
                .addGap(48, 48, 48)
                .addComponent(filePath)
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)
                                .addComponent(RLinear))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RLogistica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arvoreD)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seletorArq)
                    .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(RLinear)
                    .addComponent(RLogistica)
                    .addComponent(arvoreD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(soTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    JFileChooser fileChooser;
    String filename;
    boolean arqOk;
    
    
    private void seletorArqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorArqActionPerformed
        //faz o botão abrir um FileChooser
        arqOk = false;
        fileChooser = new JFileChooser();
        int resp;
        boolean sair = false;
        while (!arqOk && !sair) {
            resp = fileChooser.showOpenDialog(null); //seleciona file para abrir
            if (resp == JFileChooser.APPROVE_OPTION) { //se um arq foi escolhido
                filename = fileChooser.getSelectedFile().getAbsolutePath();
                int i = filename.lastIndexOf('.');
                if (i > 0) { // se tiver um ponto ponto pelo menos
                    if (filename.substring(i + 1).equals("csv")) { // se for do tipo csv
                        filePath.setText(fileChooser.getSelectedFile().getAbsolutePath());
                        arqOk = true;
                    }else
                        showMessageDialog();
                }
            } else {
                sair = true;
            }
        }
        if(arqOk)
            loadData();
    }//GEN-LAST:event_seletorArqActionPerformed

    double [][] data;
    boolean dataOk = false;
    
    private void loadData(){
        CSVReader reader = new CSVReader();
        reader.read(filename, true);
        data = reader.getData();
        dataOk = true;
    }
    
    private void showMessageDialog() {
        int ok = JOptionPane.showConfirmDialog(null, "Arquilo selecionado é invalido, selecione um arquivo .CSV", "Erro", JOptionPane.DEFAULT_OPTION);
    }
    
    Algorithm alg;
    int qualAlg;
    
    private void RLinearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RLinearActionPerformed
            soTeste.setText("linear escolhida");
            qualAlg = 0;
            if(arqOk)
                buildModel();
    }//GEN-LAST:event_RLinearActionPerformed

    private void filePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filePathActionPerformed

    private void RLogisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RLogisticaActionPerformed
          soTeste.setText("lOGISTICA escolhida");
          qualAlg = 1;
          if(arqOk)
            buildModel();
    }//GEN-LAST:event_RLogisticaActionPerformed
         
    private void soTesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soTesteActionPerformed

    }//GEN-LAST:event_soTesteActionPerformed

    private void arvoreDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arvoreDActionPerformed
         soTeste.setText("arvore escolhida");
         qualAlg = 2;
         if(arqOk)
            buildModel();
    }//GEN-LAST:event_arvoreDActionPerformed


    private void buildModel(){
        /*
        EM .trainTestSplit fazer o segundo termo ser escolhivel pelo usuario
        */
        Split spliter = new Split();
                      //botar com os espaços la
        spliter.trainTestSplit(data, 0.5, 6);
        spliter.separateFeaturesLabels(data[0].length-1);
        if(qualAlg == 0){
            alg = new LinearRegression();
            alg.setData(spliter.getTrainFeatureData(), spliter.getTrainLabelData());
            System.out.println("DATA SETADA");
        }else if(qualAlg == 1){
            alg = new LogisticRegression();
            alg.setData(spliter.getTrainFeatureData(), spliter.getTrainLabelData());
            System.out.println("DATA SETADA");
        }else{
            System.out.println("Arvore ainda não implementada");
        }
    }
    
   
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframe_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframe_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframe_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframe_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframe_Form().setVisible(true);
            }
        });
       
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RLinear;
    private javax.swing.JRadioButton RLogistica;
    private javax.swing.JRadioButton arvoreD;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField filePath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton seletorArq;
    private java.awt.TextField soTeste;
    // End of variables declaration//GEN-END:variables
}
